import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    height: '100%',
    width: '100%',
  },
  blue: {
  },
  button: {
    flex: 1,
    marginVertical: 8,
    width: 10,
  },
  buttonText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    marginHorizontal: 16,
  },
  contentContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  deleteframebutton: {
    padding: 20,
  },
  fixToText: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  frameCreator: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  framedescription: {
    alignSelf: "center",
    justifyContent: "center",
    padding: 5,
  },
  frameinput: {
    fontSize: 20,
    height: 50,
  },
  framename: {
    alignSelf: "center",
    fontSize: 20,
    fontWeight: "bold",
    justifyContent: "center",
    padding: 10,
  },
  framesbutton: {
  },
  header: {
    backgroundColor: "coral",
    borderRadius: 25,
    height: 80,
    paddingTop: 38,
  },
  homescreenbutton: {
    alignItems: "center",
    backgroundColor: "pink",
    borderRadius: 10,
    elevation: 3,
    height: 50,
    justifyContent: "center",
    marginTop: 20,
    shadowColor: 'magenta',
    shadowOffset: {
      width: 2,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    width: 210,
  },
  input: {
    alignSelf: "center",
    borderColor: "red",
    borderWidth: 2,
    flex: 1,
    fontSize: 25,
    height: 50,
    justifyContent: "center",
    padding: 0,
    textAlign: "center",
    width: 300,
  },
  melodytitle: {
    fontSize: 30,
    fontWeight: "bold",
    padding: 20,
    textAlign: "center",
  },
  picker: {
    alignSelf: "top",
    fontSize: 16,
    height: 30,
    width: 100,
  },
  red: {
    backgroundColor: "red",
  },
  separator: {
    borderBottomColor: "#737373",
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginVertical: 8,
  },
  title: {
    alignItems: "center",
    fontSize: 30,
    justifyContent: "center",
    marginVertical: 8,
    padding: 25,
    position: "relative",
    textAlign: "center",
  },
  ttsinput: {
    alignSelf: "center",
    backgroundColor: "white",
    opacity: 0.5,
    borderRadius: 5,
    fontSize: 25,
    height: 50,
    marginVertical: 10,
    padding: 0,
    textAlign: "center",
    width: 300,
  },
  ttsplaybutton: {
    alignItems: 'center',
    backgroundColor: '#2196F3',
    borderRadius: 10,
    elevation: 3,
    height: 40,
    justifyContent: 'center',
    marginVertical: 10,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 150,
  },
  ttsbuttoncontainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
  ttsbutton: {
    alignItems: 'center',
    backgroundColor: '#4CAF50',
    borderRadius: 10,
    elevation: 3,
    height: 40,
    justifyContent: 'center',
    marginVertical: 10,
    marginHorizontal: 2,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 150,
  },
  view: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  words: {
    alignContent: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  wordscontainer: {
    flex: 1,
    justifyContent: "center",
  },
});
